spring:
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/ecommerce
    username: ${DB_USER:eco}
    password: ${DB_PASSWORD:ecopass}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

security:
  jwt:
    secret-key: ${JWT_SECRET}

product:
  image:
    # Minimum and maximum number of images allowed per product
    min-count: 1
    max-count: 10
    max-size: 5MB
    allowed-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/webp