CREATE TABLE IF NOT EXISTS eco_warehouse
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    full_address VARCHAR(1000),
    created_at   TIMESTAMP(0) NOT NULL,
    updated_at   TIMESTAMP(0),
    created_by   VARCHAR(255) NOT NULL DEFAULT 'ECO',
    updated_by   VARCHAR(255),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMP(0),
    deleted_by   VARCHAR(255)
);

ALTER TABLE eco_inventory
    ADD COLUMN warehouse_id BIGINT;

ALTER TABLE eco_inventory
    ADD CONSTRAINT fk_inventory_warehouse_id
        FOREIGN KEY (warehouse_id) REFERENCES eco_warehouse (id);

ALTER TABLE eco_inventory
    ADD CONSTRAINT uq_eco_inventory_product_warehouse
        UNIQUE (product_id, warehouse_id);